import unreal
world = unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_game_world()
cls = unreal.load_object(None, "/Game/Widgets/W_AbilitiesScreen.W_AbilitiesScreen_C")
pc = unreal.GameplayStatics.get_player_controller(world, 0)
lib_cdo = unreal.WidgetLibrary.get_default_object()
screen = lib_cdo.call_method("Create", args=(world, cls, pc))
print("KB2 created: " + str(screen))
screen.add_to_viewport(100)
print("KB2 screen added: " + screen.get_name())
print("KB2 DONE")