
import unreal
bg = unreal.load_object(None, "/NarrativeInventory/NarrativeUI/WBP_EquippedItem.WBP_EquippedItem:WidgetTree.Image_BG")
tex = unreal.load_asset("/NarrativeInventory/NarrativeUI/Assets/Icons/T_DefaultItemThumb")
b = bg.get_editor_property("brush")
b.set_editor_property("resource_object", tex)
bg.set_editor_property("brush", b)
bg.set_editor_property("color_and_opacity", unreal.LinearColor(1.0,1.0,1.0,0.55))
bg.set_editor_property("render_opacity", 1.0)
b2 = bg.get_editor_property("brush")
print("AFTER resource:", b2.get_editor_property("resource_object"))
print("AFTER imgsize:", b2.get_editor_property("image_size"))
print("AFTER color:", bg.get_editor_property("color_and_opacity"))
print("AFTER renderopacity:", bg.get_editor_property("render_opacity"))
bp = unreal.load_asset("/NarrativeInventory/NarrativeUI/WBP_EquippedItem")
unreal.BlueprintEditorLibrary.compile_blueprint(bp)
print("SAVE:", unreal.EditorAssetLibrary.save_asset("/NarrativeInventory/NarrativeUI/WBP_EquippedItem", only_if_is_dirty=False))
print("DONE")
