import unreal
def L(m): unreal.log("GOLDTHUMB " + str(m))
bp_path = "/Game/Inventory/Items/BP_Item_Gold"
cls = unreal.EditorAssetLibrary.load_blueprint_class(bp_path)
cdo = unreal.get_default_object(cls)
before = cdo.get_editor_property("thumbnail")
L("before thumbnail = %s" % before)
tex = unreal.EditorAssetLibrary.load_asset("/NarrativeInventory/NarrativeUI/Assets/Icons/T_CoinIcon")
L("loaded T_CoinIcon = %s" % (tex.get_name() if tex else None))
cdo.set_editor_property("thumbnail", tex)
after = cdo.get_editor_property("thumbnail")
L("after thumbnail = %s" % after)
bp = unreal.EditorAssetLibrary.load_asset(bp_path)
unreal.BlueprintEditorLibrary.compile_blueprint(bp)
ok = unreal.EditorAssetLibrary.save_asset(bp_path)
L("saved=%s" % ok)
L("DONE_GOLDTHUMB")
