;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.AOEAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Cooldown.Shield",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Dexterity",DevComment="")
+GameplayTagList=(Tag="Data.Faith",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Data.Health",DevComment="")
+GameplayTagList=(Tag="Data.Intelligence",DevComment="")
+GameplayTagList=(Tag="Data.Mana",DevComment="")
+GameplayTagList=(Tag="Data.Stamina",DevComment="")
+GameplayTagList=(Tag="Data.StatPoints",DevComment="")
+GameplayTagList=(Tag="Debuff.Fire",DevComment="")
+GameplayTagList=(Tag="Debuff.Ice",DevComment="")
+GameplayTagList=(Tag="Effects.HitReaction",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.Effect.StackCountChanged",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger",DevComment="")
+GameplayTagList=(Tag="Event.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.AOEAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.FillShield",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.AxeSwing",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.Combo",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.WeaponAbility",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOEIndicator",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Burning",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Frozen",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.LightningBolt",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.GreenFire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.Ice",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.GreenFire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.Ice",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldBubble",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldDown",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.TargetingCamera",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Status.Attacking",DevComment="")
+GameplayTagList=(Tag="Status.Buff.Shield",DevComment="")
+GameplayTagList=(Tag="Status.Burning",DevComment="")
+GameplayTagList=(Tag="Status.Frozen",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen.Blocked",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Staff",DevComment="")

